"""Native provider shapes observed/generated by the live acceptance harness."""

from unittest.mock import AsyncMock

import pytest

from scripts.forge_trace import evidence
from tests.test_skuld.test_codex_ws_transport import _make_transport
from tests.test_skuld.test_event_log import _broker
from tests.test_skuld.test_tmux_interactive_transport import FakeTmuxInteractiveTransport


@pytest.mark.parametrize("kind", ["user_consumed", "terminal_prompt_submitted"])
async def test_consumption_and_derived_activation_have_identical_live_and_log_order(tmp_path, kind):
    broker = _broker(tmp_path)
    broker._save_conversation_history = lambda: None
    broker._report_activity_state = AsyncMock()
    live = []
    broker._channels.broadcast = AsyncMock(side_effect=lambda f: live.append(f.copy()))
    await broker._handle_cli_event({"type": kind, "msg_id": "m1"})
    assert [f["type"] for f in live] == [kind, "user_active"]
    assert [r["payload"] for r in broker._event_log_buffer] == live


@pytest.mark.parametrize(
    "child",
    [
        {"session_id": "worker-native"},
        {"agent_id": "worker"},
        {"is_sidechain": True},
        {"isSidechain": True},
        {"agentId": "worker"},
    ],
)
@pytest.mark.parametrize("hook", ["Stop", "StopFailure"])
async def test_worker_stop_cannot_end_parent_turn(tmp_path, child, hook):
    transport = FakeTmuxInteractiveTransport(str(tmp_path))
    transport._claude_native_session_id = "parent-native"
    transport._begin_turn()
    events = []
    transport.on_event(AsyncMock(side_effect=events.append))
    await transport.handle_claude_hook(
        {"hook_event_name": hook, "last_assistant_message": "worker done", **child}
    )
    assert transport._turn_active
    assert [f["type"] for f in events] == ["claude_hook"]
    await transport.handle_claude_hook(
        {
            "hook_event_name": "Stop",
            "session_id": "parent-native",
            "last_assistant_message": "parent done",
        }
    )
    assert not transport._turn_active
    assert len([f for f in events if f["type"] == "result"]) == 1


async def test_codex_native_plan_maps_to_shared_replace_snapshot(tmp_path):
    transport = _make_transport(tmp_path)
    events = []
    transport.on_event(AsyncMock(side_effect=events.append))
    await transport._handle_server_message(
        {
            "method": "turn/plan/updated",
            "params": {
                "plan": [
                    {"step": "inspect", "status": "completed"},
                    {"step": "verify", "status": "inProgress"},
                    {"step": "report", "status": "pending"},
                ]
            },
        }
    )
    plan = events[-1]
    assert plan["type"] == "plan"
    assert plan["tasks"][1] == {"content": "verify", "status": "in_progress"}
    assert plan["counts"] == {"total": 3, "pending": 1, "in_progress": 1, "completed": 1}


@pytest.mark.parametrize("status", ["completed", "failed", "interrupted"])
async def test_codex_agent_call_pairs_and_preserves_native_identity(tmp_path, status):
    transport = _make_transport(tmp_path)
    events = []
    transport.on_event(AsyncMock(side_effect=events.append))
    item = {
        "id": "spawn-1",
        "type": "collabAgentToolCall",
        "tool": "spawnAgent",
        "senderThreadId": "parent",
        "receiverThreadIds": [],
        "status": "inProgress",
        "prompt": "read the synthetic fixture",
        "agentsStates": {},
    }
    await transport._handle_item_started(item)
    item.update({"status": status, "receiverThreadIds": ["worker-1"]})
    await transport._handle_item_completed(item)
    observed = evidence(events)
    assert not observed["unpaired_calls"]
    assert observed["tool_families"]["agent"] == 1
    assert bool(observed["results"]["spawn-1"].get("is_error")) == (status != "completed")
    agents = [e for e in events if e["type"] == "agent_update"]
    assert len(agents) == int(status == "completed")
    if agents:
        assert agents[0]["agent"]["id"] == "worker-1"
        assert agents[0]["agent"]["parent_id"] == "parent"


@pytest.mark.parametrize(
    "state,expected",
    [("completed", "done"), ("errored", "failed"), ("interrupted", "failed"), ("shutdown", "done")],
)
async def test_codex_wait_closes_agent_surface_without_counting_another_spawn(
    tmp_path, state, expected
):
    transport = _make_transport(tmp_path)
    events = []
    transport.on_event(AsyncMock(side_effect=events.append))
    item = {
        "id": "wait-1",
        "type": "collabAgentToolCall",
        "tool": "wait",
        "receiverThreadIds": ["worker"],
        "senderThreadId": "parent",
        "status": "completed",
        "agentsStates": {"worker": {"status": state, "message": "finding"}},
    }
    await transport._handle_item_started(item)
    await transport._handle_item_completed(item)
    assert evidence(events)["tool_families"].get("agent", 0) == 0
    update = next(f for f in events if f["type"] == "agent_update")
    assert update["action"] == "stopped"
    assert update["agent"]["status"] == expected
    await transport._surface_collab_agents(item)
    assert len([f for f in events if f["type"] == "agent_update"]) == 1


async def request_question(transport):
    await transport._handle_server_request(
        {
            "id": 91,
            "method": "item/tool/requestUserInput",
            "params": {
                "itemId": "item",
                "questions": [
                    {
                        "id": "accent",
                        "question": "Choose accent",
                        "header": "Accent",
                        "options": [
                            {"label": "blue", "description": "first"},
                            {"label": "amber", "description": "second"},
                        ],
                    }
                ],
            },
        }
    )


async def test_codex_question_preserves_id_and_sends_explicit_second_choice(tmp_path):
    transport = _make_transport(tmp_path)
    transport._send_rpc_response = AsyncMock()
    events = []
    transport.on_event(AsyncMock(side_effect=events.append))
    await request_question(transport)
    ask = events[-1]
    assert ask["type"] == "ask_user_question"
    await transport.send_control(
        "ask_user_answer",
        request_id=ask["request_id"],
        answers=[{"question_id": "accent", "answer": "amber"}],
    )
    transport._send_rpc_response.assert_awaited_once_with(
        91, {"answers": {"accent": {"answers": ["amber"]}}}
    )
    assert events[-1]["type"] == "ask_user_resolved"
    assert not transport._pending_user_inputs
    with pytest.raises(ValueError, match="already answered"):
        await transport.send_control(
            "ask_user_answer",
            request_id=ask["request_id"],
            answers=[{"question_id": "accent", "answer": "blue"}],
        )


@pytest.mark.parametrize(
    "answer",
    [[], [{"question_id": "wrong", "answer": "blue"}], [{"question_id": "accent", "answer": ""}]],
)
async def test_codex_question_never_defaults_missing_or_wrong_answers(tmp_path, answer):
    transport = _make_transport(tmp_path)
    transport._send_rpc_response = AsyncMock()
    await request_question(transport)
    request_id = next(iter(transport._pending_user_inputs))
    with pytest.raises(ValueError):
        await transport.send_control("ask_user_answer", request_id=request_id, answers=answer)
    transport._send_rpc_response.assert_not_called()
    assert request_id in transport._pending_user_inputs


async def test_codex_question_send_failure_retains_retryable_request(tmp_path):
    transport = _make_transport(tmp_path)
    transport._send_rpc_response = AsyncMock(side_effect=ConnectionError)
    await request_question(transport)
    request_id = next(iter(transport._pending_user_inputs))
    with pytest.raises(ConnectionError):
        await transport.send_control(
            "ask_user_answer",
            request_id=request_id,
            answers=[{"question_id": "accent", "answer": "amber"}],
        )
    assert request_id in transport._pending_user_inputs


async def test_installed_codex_subagent_activity_has_real_spawn_receipt_and_finish(tmp_path):
    transport = _make_transport(tmp_path)
    transport._thread_id = "parent"
    events = []
    transport.on_event(AsyncMock(side_effect=events.append))
    item = {
        "type": "subAgentActivity",
        "id": "call-spawn",
        "kind": "started",
        "agentThreadId": "worker",
        "agentPath": "/root/worker",
    }
    await transport._handle_item_started(item)
    await transport._handle_item_completed(item)
    await transport._handle_item_completed({**item, "id": "worker-complete", "kind": "completed"})
    observed = evidence(events)
    assert observed["tool_families"]["agent"] == 1
    assert not observed["unpaired_calls"]
    assert observed["agent_ids"] == ["worker"]
    assert [f["action"] for f in events if f["type"] == "agent_update"] == ["started", "stopped"]


async def test_codex_child_turn_events_cannot_finalize_or_pollute_parent(tmp_path):
    transport = _make_transport(tmp_path)
    transport._thread_id = "parent"
    transport._current_turn_id = "parent-turn"
    events = []
    transport.on_event(AsyncMock(side_effect=events.append))
    for method, params in [
        ("item/agentMessage/delta", {"delta": "child text"}),
        ("turn/completed", {"turn": {"id": "child-turn", "status": "completed"}}),
    ]:
        await transport._handle_server_message(
            {"method": method, "params": {"threadId": "child", **params}}
        )
    assert transport._current_turn_id == "parent-turn"
    assert [f["type"] for f in events] == ["agent_event", "agent_event"]
    assert events[-1]["payload"]["turn"]["id"] == "child-turn"


async def test_codex_async_question_maps_second_option_to_native_steering(tmp_path):
    transport = _make_transport(tmp_path)
    transport._thread_id = "parent"
    transport._current_turn_id = "turn"
    transport._send_rpc = AsyncMock(return_value={})
    events = []
    transport.on_event(AsyncMock(side_effect=events.append))
    await transport._handle_item_completed(
        {
            "type": "agentMessage",
            "id": "question-call",
            "delivery": "async",
            "questions": [{"title": "Which accent?", "options": ["blue", "amber"]}],
        }
    )
    ask = events[-1]
    assert ask["questions"][0]["options"][1]["label"] == "amber"
    await transport.send_control(
        "ask_user_answer",
        request_id=ask["request_id"],
        answers=[{"question_id": "question-call:0", "answer": "amber"}],
    )
    method, params = transport._send_rpc.await_args.args
    assert method == "turn/steer"
    assert params["input"][0]["text"] == "Which accent?: amber"
    assert not transport._pending_user_inputs


async def test_codex_disconnect_resolves_questions_and_running_agents_once(tmp_path):
    transport = _make_transport(tmp_path)
    transport._current_turn_id = "turn"
    transport._pending_user_inputs = {"question": (None, [])}
    transport._agent_states = {"worker": "running", "finished": "completed"}
    events = []
    transport.on_event(AsyncMock(side_effect=events.append))
    await transport._finalize_stranded_turn("error", "socket lost")
    await transport._finalize_stranded_turn("error", "socket lost")
    assert [f["type"] for f in events] == ["ask_user_resolved", "agent_update", "result"]
    assert events[1]["agent"] == {"id": "worker", "kind": "subagent", "status": "failed"}
    assert not transport._pending_user_inputs
    assert not transport._agent_states
