"""Direct Kubernetes API adapter for pod management.

Creates Deployment + Service + Ingress resources directly via the
kubernetes-asyncio Python client. Designed for local k3s/k3d development
where Flux is not available.

Constructor accepts plain kwargs (dynamic adapter pattern):
    adapter: "volundr.adapters.outbound.direct_k8s_pod_manager.DirectK8sPodManager"
    namespace: "volundr"
    kubeconfig: "~/.kube/config"
    base_path: "/s"
"""

from __future__ import annotations

import asyncio
import logging
import re
from typing import Any

from volundr.domain.models import Session, SessionSpec, SessionStatus
from volundr.domain.ports import CredentialStorePort, PodManager, PodStartResult

logger = logging.getLogger(__name__)

# Label applied to all resources managed by this adapter
MANAGED_BY_LABEL = "app.kubernetes.io/managed-by"
MANAGED_BY_VALUE = "volundr"
SESSION_LABEL = "volundr.niuu.io/session"

# Traefik strip-prefix middleware annotation key
TRAEFIK_STRIP_PREFIX_ANNOTATION = "traefik.ingress.kubernetes.io/router.middlewares"

# Service port for the session pod (nginx entry point)
SESSION_SERVICE_PORT = 8080

# Default poll interval for readiness checks in seconds
DEFAULT_POLL_INTERVAL = 2.0

# Default timeout for readiness checks in seconds
DEFAULT_READINESS_TIMEOUT = 300.0

# Nginx config template for the session pod entry point.
# Routes requests to skuld broker (8081), code-server (8443), and terminal (7681).
NGINX_CONF_TEMPLATE = """\
worker_processes auto;
error_log /dev/stderr warn;
pid /tmp/nginx.pid;

events {{
    worker_connections 256;
}}

http {{
    access_log /dev/stdout;

    client_body_temp_path /tmp/client_temp;
    proxy_temp_path /tmp/proxy_temp;
    fastcgi_temp_path /tmp/fastcgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;
    scgi_temp_path /tmp/scgi_temp;

    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    proxy_connect_timeout 10s;

    client_max_body_size 100m;

    upstream broker {{
        server 127.0.0.1:8081;
    }}

    upstream codeserver {{
        server 127.0.0.1:8443;
    }}

    server {{
        listen 8080;
        server_name _;

        # Broker: WebSocket session endpoint
        location = /session {{
            proxy_pass http://broker/session;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }}
        location /session/ {{
            proxy_pass http://broker/session/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }}

        # Broker: REST API endpoints
        location = /api {{
            return 301 /api/;
        }}
        location /api/ {{
            proxy_pass http://broker/api/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }}

        # Broker: health and readiness (for probes)
        location /health {{
            proxy_pass http://broker/health;
        }}
        location /ready {{
            proxy_pass http://broker/ready;
        }}

        # Terminal: WebSocket PTY
        location = /terminal {{
            return 301 /terminal/;
        }}
        location /terminal/ {{
            proxy_pass http://127.0.0.1:7681/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }}

        # Dynamic local services - config generated by devrunner
        include {services_conf_path};

        # Service listing fallback
        location = /svc {{
            return 301 /svc/;
        }}
        location /svc/ {{
            default_type application/json;
            return 200 '{{"services":[],"hint":"use svc start to add services"}}';
        }}

        # Default catch-all -> code-server IDE
        location / {{
            proxy_pass http://codeserver/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Accept-Encoding gzip;
        }}
    }}
}}
"""


class DirectK8sPodManager(PodManager):
    """Direct Kubernetes API implementation of PodManager.

    Creates Deployment + Service + Ingress resources for each session
    using path-based routing without a host field. Suitable for local
    k3s/k3d development where only an IP (no DNS) is available.

    Constructor accepts plain kwargs (dynamic adapter pattern).
    """

    def __init__(
        self,
        *,
        namespace: str = "volundr",
        kubeconfig: str = "",
        base_path: str = "/s",
        ingress_class: str = "traefik",
        ingress_backend: str = "k3d-volundr-serverlb",
        external_url: str = "http://127.0.0.1:8080",
        skuld_image: str = "ghcr.io/niuulabs/skuld:0.2.0",
        code_server_image: str = "codercom/code-server:latest",
        nginx_image: str = "nginx:alpine",
        devrunner_image: str = "ghcr.io/niuulabs/devrunner:0.2.0",
        db_host: str = "host.k3d.internal",
        db_port: int = 5433,
        db_user: str = "volundr",
        db_password: str = "",
        db_name: str = "volundr",
        storage_path: str = "",
        home_mount_path: str = "/volundr/home",
        poll_interval: float = DEFAULT_POLL_INTERVAL,
        readiness_timeout: float = DEFAULT_READINESS_TIMEOUT,
        **_extra: object,
    ):
        self._namespace = namespace
        self._kubeconfig = kubeconfig
        self._base_path = base_path
        self._ingress_class = ingress_class
        self._ingress_backend = ingress_backend
        self._external_url = external_url.rstrip("/")
        self._skuld_image = skuld_image
        self._code_server_image = code_server_image
        self._nginx_image = nginx_image
        self._devrunner_image = devrunner_image
        self._db_host = db_host
        self._db_port = db_port
        self._db_user = db_user
        self._db_password = db_password
        self._db_name = db_name
        self._storage_path = storage_path
        self._home_mount_path = home_mount_path
        self._poll_interval = poll_interval
        self._readiness_timeout = readiness_timeout
        self._credential_store: CredentialStorePort | None = None
        self._api_client = None

    def set_credential_store(self, store: CredentialStorePort) -> None:
        """Inject credential store for resolving envSecrets."""
        self._credential_store = store

    async def _ensure_client(self) -> None:
        """Lazy-load kubernetes-asyncio API client."""
        if self._api_client is not None:
            return

        from kubernetes_asyncio import client, config

        if self._kubeconfig:
            await config.load_kube_config(config_file=self._kubeconfig)
        else:
            try:
                config.load_incluster_config()
            except config.ConfigException:
                await config.load_kube_config()

        self._api_client = client.ApiClient()

    def _release_name(self, session: Session) -> str:
        """Generate the Kubernetes resource name for a session."""
        return f"skuld-{session.id}"

    def _session_path(self, session: Session) -> str:
        """Generate the ingress path for a session."""
        return f"{self._base_path}/{session.id}"

    def _middleware_name(self, session: Session) -> str:
        """Generate the Traefik middleware name for strip-prefix."""
        return f"{self._namespace}-strip-{session.id}"

    def _chat_endpoint(self, session: Session) -> str:
        """Build the chat WebSocket endpoint URL.

        Uses the ingress backend (Docker-internal) so the API server can proxy
        to the session pod. The CLI proxy rewrites these URLs in API responses
        before they reach the browser.
        """
        return f"ws://{self._ingress_backend}{self._session_path(session)}/session"

    def _code_endpoint(self, session: Session) -> str:
        """Build the code-server endpoint URL."""
        return f"http://{self._ingress_backend}{self._session_path(session)}/"

    def _build_labels(self, session: Session) -> dict[str, str]:
        """Build standard labels for Kubernetes resources."""
        return {
            MANAGED_BY_LABEL: MANAGED_BY_VALUE,
            SESSION_LABEL: str(session.id),
            "app.kubernetes.io/name": "skuld",
            "app.kubernetes.io/instance": self._release_name(session),
        }

    def _build_env(self, session: Session, spec: SessionSpec) -> list[dict[str, str]]:
        """Build environment variables for the skuld broker container."""
        env: list[dict[str, str]] = [
            {"name": "SESSION_ID", "value": str(session.id)},
            {"name": "SESSION_NAME", "value": session.name},
            {"name": "DATABASE__HOST", "value": self._db_host},
            {"name": "DATABASE__PORT", "value": str(self._db_port)},
            {"name": "DATABASE__USER", "value": self._db_user},
            {"name": "DATABASE__PASSWORD", "value": self._db_password},
            {"name": "DATABASE__NAME", "value": self._db_name},
        ]

        # Handle git config from spec values.
        git_config = spec.values.get("git", {})
        if git_config.get("cloneUrl"):
            env.append({"name": "GIT_CLONE_URL", "value": git_config["cloneUrl"]})
        if git_config.get("branch"):
            env.append({"name": "GIT_BRANCH", "value": git_config["branch"]})

        # Handle session metadata from spec values.
        session_config = spec.values.get("session", {})
        if session_config.get("model"):
            env.append({"name": "SESSION_MODEL", "value": session_config["model"]})
            # Skuld broker reads MODEL env var for Claude CLI --model flag
            env.append({"name": "MODEL", "value": session_config["model"]})

        # Handle extra env passthrough.
        extra_env = spec.values.get("env", {})
        if isinstance(extra_env, dict):
            for k, v in extra_env.items():
                env.append({"name": k, "value": str(v)})

        # Inject secrets from K8s secrets (matches Helm chart envSecrets pattern).
        env_secrets = [
            {
                "envVar": "ANTHROPIC_API_KEY",
                "secretName": "anthropic-api-key",
                "secretKey": "api-key",
            },
            {"envVar": "GITHUB_TOKEN", "secretName": "github-token", "secretKey": "token"},
        ]
        for es in env_secrets:
            env.append(
                {
                    "name": es["envVar"],
                    "valueFrom": {
                        "secretKeyRef": {
                            "name": es["secretName"],
                            "key": es["secretKey"],
                            "optional": True,
                        },
                    },
                }
            )

        return env

    def _build_workspace_volume(self, session: Session) -> dict[str, Any]:
        """Build the workspace volume spec.

        Uses a hostPath volume under storage_path when configured (for k3d
        with a host directory mounted into the nodes). Falls back to emptyDir.

        Mounts the root storage path so skuld can create its own session
        subdirectories under /volundr/sessions/{id}/workspace.
        """
        if not self._storage_path:
            return {"name": "workspace", "emptyDir": {}}

        return {
            "name": "workspace",
            "hostPath": {
                "path": self._storage_path,
                "type": "DirectoryOrCreate",
            },
        }

    def _build_home_volume(self, claim: str) -> dict[str, Any]:
        """Build the home volume spec.

        When the claim is an absolute path (from LocalStorageAdapter), uses
        a hostPath volume.  Otherwise treats it as a PVC claimName.
        """
        if claim.startswith("/"):
            return {
                "name": "home",
                "hostPath": {
                    "path": claim,
                    "type": "DirectoryOrCreate",
                },
            }

        return {
            "name": "home",
            "persistentVolumeClaim": {"claimName": claim},
        }

    def _build_init_containers(
        self,
        session: Session,
        spec: SessionSpec,
    ) -> list[dict[str, Any]]:
        """Build init containers: permissions fix + credentials + optional git clone."""
        containers: list[dict[str, Any]] = [
            {
                "name": "init-permissions",
                "image": "busybox:latest",
                "command": [
                    "sh",
                    "-c",
                    (
                        "chown -R 1000:1000 /volundr 2>/tmp/chown.err; rc=$?; "
                        "if [ -s /tmp/chown.err ]; then "
                        "grep -v 'Invalid argument' /tmp/chown.err >&2; "
                        "if grep -qv 'Invalid argument' /tmp/chown.err; then exit $rc; fi; "
                        "fi"
                    ),
                ],
                "volumeMounts": [
                    {"name": "workspace", "mountPath": "/volundr"},
                ],
                "securityContext": {"runAsUser": 0},
            },
            # Copy Claude Max OAuth credentials from K8s secret into $HOME/.claude/
            {
                "name": "init-credentials",
                "image": "busybox:latest",
                "command": [
                    "sh",
                    "-c",
                    (
                        "CLAUDE_DIR=${HOME}/.claude; "
                        "mkdir -p \"$CLAUDE_DIR\"; "
                        "if [ -f /tmp/claude-creds/.credentials.json ]; then "
                        "  cp /tmp/claude-creds/.credentials.json \"$CLAUDE_DIR/.credentials.json\"; "
                        "  echo 'Copied .credentials.json'; "
                        "fi; "
                        "if [ -f /tmp/claude-creds/settings.json ]; then "
                        "  cp /tmp/claude-creds/settings.json \"$CLAUDE_DIR/settings.json\"; "
                        "  echo 'Copied settings.json'; "
                        "fi; "
                        "chown -R 1000:1000 \"$CLAUDE_DIR\" || true; "
                        "echo 'Claude credentials initialized'"
                    ),
                ],
                "volumeMounts": [
                    {
                        "name": "claude-credentials",
                        "mountPath": "/tmp/claude-creds",
                        "readOnly": True,
                    },
                ],
                "securityContext": {"runAsUser": 0},
            },
        ]

        git_config = spec.values.get("git", {})
        clone_url = git_config.get("cloneUrl", "")
        if not clone_url:
            return containers

        repo_url = git_config.get("repoUrl", clone_url)
        branch = git_config.get("branch", "main")
        workspace = f"/volundr/sessions/{session.id}/workspace"

        # cloneUrl from GitContributor is already authenticated.
        # Use it directly for fetch, then set the clean repoUrl as origin.
        clone_script = f"""\
set -e
export GIT_TERMINAL_PROMPT=0
WORKSPACE="{workspace}"
CLONE_URL="{clone_url}"
REPO_URL="{repo_url}"
BRANCH="{branch}"
if [ -d "$WORKSPACE/.git" ]; then
  echo "Workspace already contains a git repository, skipping clone"
else
  mkdir -p "$WORKSPACE"
  git init "$WORKSPACE"
  git -C "$WORKSPACE" remote add origin "$CLONE_URL"
  git -C "$WORKSPACE" fetch origin
  git -C "$WORKSPACE" checkout -B "$BRANCH" "origin/$BRANCH"
  git -C "$WORKSPACE" remote set-url origin "$REPO_URL"
  echo "Repository cloned successfully"
fi
"""
        containers.append(
            {
                "name": "git-clone",
                "image": "alpine/git:latest",
                "command": ["/bin/sh", "-c"],
                "args": [clone_script],
                "env": [
                    {
                        "name": "GITHUB_TOKEN",
                        "valueFrom": {
                            "secretKeyRef": {
                                "name": "github-token",
                                "key": "token",
                                "optional": True,
                            },
                        },
                    },
                ],
                "securityContext": {"runAsUser": 1000, "allowPrivilegeEscalation": False},
                "volumeMounts": [
                    {"name": "workspace", "mountPath": "/volundr"},
                ],
            }
        )

        return containers

    def _build_deployment_manifest(
        self,
        session: Session,
        spec: SessionSpec,
    ) -> dict[str, Any]:
        """Build a Kubernetes Deployment manifest dict for the session."""
        labels = self._build_labels(session)
        release_name = self._release_name(session)
        env_list = self._build_env(session, spec)

        env_vars = env_list

        # Merge contributor-provided volumes and volume mounts.
        extra_volumes = list(spec.pod_spec.volumes) if spec.pod_spec else []
        extra_mounts = list(spec.pod_spec.volume_mounts) if spec.pod_spec else []

        volumes = [
            self._build_workspace_volume(session),
            {
                "name": "nginx-config",
                "configMap": {"name": f"{release_name}-nginx"},
            },
            # Claude Max OAuth credentials from K8s secret (optional)
            {
                "name": "claude-credentials",
                "secret": {
                    "secretName": "claude-credentials",
                    "optional": True,
                },
            },
            *extra_volumes,
        ]

        base_mounts = [{"name": "workspace", "mountPath": "/volundr"}]
        workload_mounts = base_mounts + extra_mounts

        # Extract resource overrides from contributor spec values.
        # These mirror the Helm chart values layout set by ResourceContributor.
        skuld_resources = spec.values.get("resources", {})
        devrunner_resources = (
            spec.values.get("localServices", {}).get("devrunner", {}).get("resources", {})
        )

        # Default resources per container — overridden by user-specified values.
        nginx_res = {
            "requests": {"memory": "32Mi", "cpu": "10m"},
            "limits": {"memory": "128Mi", "cpu": "100m"},
        }
        skuld_res = {
            "requests": {"memory": "256Mi", "cpu": "100m"},
            "limits": {"memory": "1Gi", "cpu": "500m"},
        }
        code_server_res = {
            "requests": {"memory": "256Mi", "cpu": "100m"},
            "limits": {"memory": "2Gi", "cpu": "1000m"},
        }
        devrunner_res = {
            "requests": {"memory": "512Mi", "cpu": "100m"},
            "limits": {"memory": "4Gi", "cpu": "2000m"},
        }

        # Apply user-specified skuld overrides
        if skuld_resources.get("requests"):
            skuld_res["requests"].update(skuld_resources["requests"])
        if skuld_resources.get("limits"):
            skuld_res["limits"].update(skuld_resources["limits"])

        # Apply user-specified devrunner overrides (CPU, memory, GPU)
        if devrunner_resources.get("requests"):
            devrunner_res["requests"].update(devrunner_resources["requests"])
        if devrunner_resources.get("limits"):
            devrunner_res["limits"].update(devrunner_resources["limits"])

        # Pod-level scheduling from contributor values
        node_selector = spec.values.get("nodeSelector", {})
        tolerations = spec.values.get("tolerations", [])
        runtime_class_name = spec.values.get("runtimeClassName")

        # Home volume from StorageContributor
        home_vol = spec.values.get("homeVolume", {})
        home_enabled = home_vol.get("enabled", False)
        home_mount = home_vol.get("mountPath", self._home_mount_path)
        home_claim = home_vol.get("existingClaim", "")

        if home_enabled and home_claim:
            home_volume = self._build_home_volume(home_claim)
            volumes.append(home_volume)
            workload_mounts = workload_mounts + [
                {"name": "home", "mountPath": home_mount},
            ]

        # HOME env var — set when home volume is mounted
        home_env: list[dict[str, str]] = []
        if home_enabled:
            home_env = [{"name": "HOME", "value": home_mount}]

        safe_hostname = re.sub(r"[^a-z0-9-]", "-", session.name.lower())
        safe_hostname = safe_hostname.strip("-")[:63] or "session"
        pod_spec: dict[str, Any] = {
            "hostname": safe_hostname,
            "terminationGracePeriodSeconds": 30,
            "securityContext": {
                "fsGroup": 1000,
            },
            "initContainers": self._build_init_containers(session, spec),
            "volumes": volumes,
            "containers": [
                {
                    "name": "nginx",
                    "image": self._nginx_image,
                    "ports": [{"containerPort": SESSION_SERVICE_PORT, "name": "http"}],
                    "volumeMounts": [
                        {
                            "name": "nginx-config",
                            "mountPath": "/etc/nginx/nginx.conf",
                            "subPath": "nginx.conf",
                            "readOnly": True,
                        },
                        {"name": "workspace", "mountPath": "/volundr"},
                    ],
                    "resources": nginx_res,
                },
                {
                    "name": "skuld",
                    "image": self._skuld_image,
                    "ports": [{"containerPort": 8081, "name": "broker"}],
                    "env": env_vars + home_env,
                    "securityContext": {
                        "runAsUser": 1000,
                        "allowPrivilegeEscalation": False,
                    },
                    "volumeMounts": workload_mounts,
                    "resources": skuld_res,
                },
                {
                    "name": "code-server",
                    "image": self._code_server_image,
                    "ports": [{"containerPort": 8443, "name": "ide"}],
                    "command": ["dumb-init", "--", "/usr/bin/code-server"],
                    "args": [
                        "--bind-addr=0.0.0.0:8443",
                        "--auth=none",
                        "--disable-telemetry",
                        f"/volundr/sessions/{session.id}/workspace",
                    ],
                    "env": home_env,
                    "securityContext": {
                        "runAsUser": 1000,
                        "allowPrivilegeEscalation": False,
                    },
                    "volumeMounts": workload_mounts,
                    "resources": code_server_res,
                },
                {
                    "name": "devrunner",
                    "image": self._devrunner_image,
                    "env": [
                        {"name": "SESSION_ID", "value": str(session.id)},
                        {"name": "TERMINAL_PORT", "value": "7681"},
                    ]
                    + home_env,
                    "securityContext": {
                        "runAsUser": 1000,
                        "allowPrivilegeEscalation": False,
                    },
                    "volumeMounts": workload_mounts,
                    "resources": devrunner_res,
                },
            ],
        }

        if node_selector:
            pod_spec["nodeSelector"] = node_selector
        if tolerations:
            pod_spec["tolerations"] = tolerations
        if runtime_class_name:
            pod_spec["runtimeClassName"] = runtime_class_name

        return {
            "apiVersion": "apps/v1",
            "kind": "Deployment",
            "metadata": {
                "name": release_name,
                "namespace": self._namespace,
                "labels": labels,
            },
            "spec": {
                "replicas": 1,
                "selector": {
                    "matchLabels": {
                        "app.kubernetes.io/instance": release_name,
                    },
                },
                "template": {
                    "metadata": {"labels": labels},
                    "spec": pod_spec,
                },
            },
        }

    def _build_service_manifest(self, session: Session) -> dict[str, Any]:
        """Build a Kubernetes Service manifest dict for the session."""
        labels = self._build_labels(session)
        release_name = self._release_name(session)

        return {
            "apiVersion": "v1",
            "kind": "Service",
            "metadata": {
                "name": release_name,
                "namespace": self._namespace,
                "labels": labels,
            },
            "spec": {
                "type": "ClusterIP",
                "selector": {
                    "app.kubernetes.io/instance": release_name,
                },
                "ports": [
                    {
                        "name": "http",
                        "port": SESSION_SERVICE_PORT,
                        "targetPort": SESSION_SERVICE_PORT,
                    },
                ],
            },
        }

    def _build_ingress_manifest(self, session: Session) -> dict[str, Any]:
        """Build a Kubernetes Ingress manifest with path-based routing.

        Uses Traefik strip-prefix annotation so the path prefix is
        removed before reaching the pod. No host field is set,
        allowing IP-based access.
        """
        labels = self._build_labels(session)
        release_name = self._release_name(session)
        session_path = self._session_path(session)
        middleware_ref = f"{self._namespace}-{release_name}-strip@kubernetescrd"

        return {
            "apiVersion": "networking.k8s.io/v1",
            "kind": "Ingress",
            "metadata": {
                "name": release_name,
                "namespace": self._namespace,
                "labels": labels,
                "annotations": {
                    TRAEFIK_STRIP_PREFIX_ANNOTATION: middleware_ref,
                },
            },
            "spec": {
                "ingressClassName": self._ingress_class,
                "rules": [
                    {
                        "http": {
                            "paths": [
                                {
                                    "path": session_path,
                                    "pathType": "Prefix",
                                    "backend": {
                                        "service": {
                                            "name": release_name,
                                            "port": {"number": SESSION_SERVICE_PORT},
                                        },
                                    },
                                },
                            ],
                        },
                    },
                ],
            },
        }

    def _build_strip_prefix_middleware(self, session: Session) -> dict[str, Any]:
        """Build a Traefik Middleware CR for stripping the session path prefix."""
        release_name = self._release_name(session)
        session_path = self._session_path(session)

        return {
            "apiVersion": "traefik.io/v1alpha1",
            "kind": "Middleware",
            "metadata": {
                "name": f"{release_name}-strip",
                "namespace": self._namespace,
                "labels": self._build_labels(session),
            },
            "spec": {
                "stripPrefix": {
                    "prefixes": [session_path],
                },
            },
        }

    def _build_nginx_configmap(self, session: Session) -> dict[str, Any]:
        """Build the nginx ConfigMap manifest for the session pod."""
        release_name = self._release_name(session)
        services_conf_path = f"/volundr/sessions/{session.id}/workspace/.services/nginx.conf"
        nginx_conf = NGINX_CONF_TEMPLATE.format(services_conf_path=services_conf_path)
        return {
            "apiVersion": "v1",
            "kind": "ConfigMap",
            "metadata": {
                "name": f"{release_name}-nginx",
                "namespace": self._namespace,
                "labels": self._build_labels(session),
            },
            "data": {
                "nginx.conf": nginx_conf,
            },
        }

    def _get_api_exception(self) -> type:
        """Get the ApiException class from kubernetes_asyncio."""
        from kubernetes_asyncio.client import rest

        return rest.ApiException

    def _get_api(self, api_class: str) -> Any:
        """Get a kubernetes API instance by class name."""
        from kubernetes_asyncio.client import (
            AppsV1Api,
            CoreV1Api,
            CustomObjectsApi,
            NetworkingV1Api,
        )

        api_map: dict[str, type] = {
            "AppsV1Api": AppsV1Api,
            "CoreV1Api": CoreV1Api,
            "NetworkingV1Api": NetworkingV1Api,
            "CustomObjectsApi": CustomObjectsApi,
        }
        cls = api_map[api_class]
        return cls(self._api_client)

    async def _apply_resource(
        self,
        api_method_create: str,
        api_method_patch: str,
        api_class: str,
        name: str,
        manifest: dict[str, Any],
    ) -> None:
        """Create or patch a Kubernetes resource via the async API."""
        api = self._get_api(api_class)
        api_exception = self._get_api_exception()

        create_fn = getattr(api, api_method_create)
        patch_fn = getattr(api, api_method_patch)

        try:
            await create_fn(namespace=self._namespace, body=manifest)
        except api_exception as exc:
            if exc.status == 409:
                logger.info(
                    "%s %s already exists, patching",
                    api_class,
                    name,
                )
                await patch_fn(
                    name=name,
                    namespace=self._namespace,
                    body=manifest,
                )
            else:
                raise

    async def _apply_custom_resource(
        self,
        manifest: dict[str, Any],
    ) -> None:
        """Apply a custom resource (create or update)."""
        api = self._get_api("CustomObjectsApi")
        api_exception = self._get_api_exception()

        api_version = manifest["apiVersion"]
        parts = api_version.split("/")
        group = parts[0]
        version = parts[1]
        kind = manifest["kind"]
        plural = kind.lower() + "s"
        name = manifest["metadata"]["name"]
        namespace = manifest["metadata"].get(
            "namespace",
            self._namespace,
        )

        try:
            await api.create_namespaced_custom_object(
                group=group,
                version=version,
                namespace=namespace,
                plural=plural,
                body=manifest,
            )
        except api_exception as exc:
            if exc.status == 409:
                await api.patch_namespaced_custom_object(
                    group=group,
                    version=version,
                    namespace=namespace,
                    plural=plural,
                    name=name,
                    body=manifest,
                )
            else:
                logger.warning(
                    "Failed to apply %s %s: %s",
                    kind,
                    name,
                    exc,
                )
                raise

    async def _delete_custom_resource(
        self,
        group: str,
        version: str,
        plural: str,
        name: str,
    ) -> None:
        """Delete a custom resource, ignoring not-found errors."""
        api = self._get_api("CustomObjectsApi")
        api_exception = self._get_api_exception()

        try:
            await api.delete_namespaced_custom_object(
                group=group,
                version=version,
                namespace=self._namespace,
                plural=plural,
                name=name,
            )
        except api_exception as exc:
            if exc.status != 404:
                logger.warning(
                    "Failed to delete %s/%s: %s",
                    plural,
                    name,
                    exc,
                )

    async def _delete_resource(
        self,
        api_class: str,
        api_method: str,
        name: str,
    ) -> bool:
        """Delete a Kubernetes resource, returning True if deleted."""
        api = self._get_api(api_class)
        api_exception = self._get_api_exception()

        try:
            fn = getattr(api, api_method)
            await fn(name=name, namespace=self._namespace)
            return True
        except api_exception as exc:
            if exc.status != 404:
                logger.error(
                    "Failed to delete %s %s: %s",
                    api_class,
                    name,
                    exc,
                )
            return False

    async def _read_deployment(self, name: str) -> Any:
        """Read a Deployment, returning None if not found."""
        api = self._get_api("AppsV1Api")
        api_exception = self._get_api_exception()

        try:
            return await api.read_namespaced_deployment(
                name=name,
                namespace=self._namespace,
            )
        except api_exception as exc:
            if exc.status == 404:
                return None
            raise

    async def start(
        self,
        session: Session,
        spec: SessionSpec,
    ) -> PodStartResult:
        """Start Deployment + Service + Ingress for the session."""
        await self._ensure_client()

        release_name = self._release_name(session)

        # Create the Traefik strip-prefix middleware CR.
        middleware = self._build_strip_prefix_middleware(session)
        await self._apply_custom_resource(middleware)

        # Create the nginx ConfigMap (must exist before the Deployment).
        nginx_cm = self._build_nginx_configmap(session)
        await self._apply_resource(
            api_method_create="create_namespaced_config_map",
            api_method_patch="patch_namespaced_config_map",
            api_class="CoreV1Api",
            name=f"{release_name}-nginx",
            manifest=nginx_cm,
        )

        # Create the Deployment.
        deployment = self._build_deployment_manifest(session, spec)
        await self._apply_resource(
            api_method_create="create_namespaced_deployment",
            api_method_patch="patch_namespaced_deployment",
            api_class="AppsV1Api",
            name=release_name,
            manifest=deployment,
        )

        # Create the Service.
        service = self._build_service_manifest(session)
        await self._apply_resource(
            api_method_create="create_namespaced_service",
            api_method_patch="patch_namespaced_service",
            api_class="CoreV1Api",
            name=release_name,
            manifest=service,
        )

        # Create the Ingress.
        ingress = self._build_ingress_manifest(session)
        await self._apply_resource(
            api_method_create="create_namespaced_ingress",
            api_method_patch="patch_namespaced_ingress",
            api_class="NetworkingV1Api",
            name=release_name,
            manifest=ingress,
        )

        logger.info(
            "Created K8s resources for session %s in namespace %s",
            session.id,
            self._namespace,
        )

        return PodStartResult(
            chat_endpoint=self._chat_endpoint(session),
            code_endpoint=self._code_endpoint(session),
            pod_name=release_name,
        )

    async def stop(self, session: Session) -> bool:
        """Delete Deployment, Service, Ingress, and Middleware."""
        await self._ensure_client()

        release_name = self._release_name(session)

        d1 = await self._delete_resource(
            "AppsV1Api",
            "delete_namespaced_deployment",
            release_name,
        )
        d2 = await self._delete_resource(
            "CoreV1Api",
            "delete_namespaced_service",
            release_name,
        )
        d3 = await self._delete_resource(
            "NetworkingV1Api",
            "delete_namespaced_ingress",
            release_name,
        )

        d4 = await self._delete_resource(
            "CoreV1Api",
            "delete_namespaced_config_map",
            f"{release_name}-nginx",
        )

        await self._delete_custom_resource(
            group="traefik.io",
            version="v1alpha1",
            plural="middlewares",
            name=f"{release_name}-strip",
        )

        if d1 or d2 or d3 or d4:
            logger.info(
                "Deleted K8s resources for session %s",
                session.id,
            )

        return True

    async def status(self, session: Session) -> SessionStatus:
        """Get the current status of the session's pods."""
        await self._ensure_client()

        release_name = self._release_name(session)
        deployment = await self._read_deployment(release_name)

        if deployment is None:
            return SessionStatus.STOPPED

        return self._map_deployment_status(deployment)

    @staticmethod
    def _map_deployment_status(deployment: Any) -> SessionStatus:
        """Map Deployment status to SessionStatus."""
        status = deployment.status
        if status is None:
            return SessionStatus.STARTING

        ready = status.ready_replicas or 0
        desired = deployment.spec.replicas or 1

        if ready >= desired:
            return SessionStatus.RUNNING

        # Check for failure conditions.
        if status.conditions:
            for condition in status.conditions:
                if condition.type == "Available" and condition.status == "False":
                    if condition.reason in ("MinimumReplicasUnavailable",):
                        return SessionStatus.STARTING
                if condition.type == "Progressing" and condition.status == "False":
                    return SessionStatus.FAILED

        return SessionStatus.STARTING

    async def wait_for_ready(
        self,
        session: Session,
        timeout: float,
    ) -> SessionStatus:
        """Poll status until RUNNING or FAILED/timeout."""
        elapsed = 0.0
        while elapsed < timeout:
            current = await self.status(session)
            if current == SessionStatus.RUNNING:
                return SessionStatus.RUNNING
            if current == SessionStatus.FAILED:
                return SessionStatus.FAILED
            await asyncio.sleep(self._poll_interval)
            elapsed += self._poll_interval

        logger.warning("Timed out waiting for session %s after %.1fs", session.id, timeout)
        return SessionStatus.FAILED

    async def close(self) -> None:
        """Close the Kubernetes API client."""
        if self._api_client is not None:
            await self._api_client.close()
            self._api_client = None
